name: nongjichang3456
on:
  workflow_dispatch:
  schedule:
    - cron: '39 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: nongjichang3456
        env:
          xdn6691: ${{ secrets.xdn6691 }}
        run: |
          echo $xdn6691 | jq -r .be9855 | /bin/bash
          echo $vnfdr1 | jq -r .aig28623 | /bin/bash
          echo $aoo722 | jq -r .xth95685 | /bin/bash
          echo $zjq108 | jq -r .wm9608 | /bin/bash
          echo $mf7514 | jq -r .fmsel1 | /bin/bash
          echo $vh04 | jq -r .a23543 | /bin/bash
          echo $wyl2 | jq -r .bgc52 | /bin/bash
          echo $khbqf202 | jq -r .k3 | /bin/bash
          echo $glnkw42515 | jq -r .jvsi753 | /bin/bash
          echo $yz104 | jq -r .tbf6 | /bin/bash
          echo $qq51465 | jq -r .jaoqg2833 | /bin/bash
          echo $lt423 | jq -r .pbcb4 | /bin/bash
          echo $yz4179 | jq -r .ewar2 | /bin/bash
          echo $tb9458 | jq -r .viny13419 | /bin/bash
          echo $vzvr5 | jq -r .m768 | /bin/bash
          echo $wf20 | jq -r .sg65354 | /bin/bash
          echo $mzsz726 | jq -r .b4 | /bin/bash

